minial_roll.minial_roll_game_element_type.*:
  type: config_entity
  label: 'GameElement type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_faction_type.*:
  type: config_entity
  label: 'Faction type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_armour_type.*:
  type: config_entity
  label: 'Armour type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_character_type.*:
  type: config_entity
  label: 'Character type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_weapon_type.*:
  type: config_entity
  label: 'Weapon type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_ability_type.*:
  type: config_entity
  label: 'Ability type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string

minial_roll.minial_roll_model_type.*:
  type: config_entity
  label: 'Model type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
