# Schema for the configuration files of the Minial roll module.
minial_roll.settings:
  type: config_object
  label: 'Minial roll settings'
  mapping:
    example:
      type: string
      label: 'Example'

entity_reference_selection.minial_roll_faction_selection:
  type: entity_reference_selection.default
  label: 'Minial Roll Game Element Selection handler settings'

entity_reference_selection.minial_roll_game_element_selection:
  type: entity_reference_selection.default
  label: 'Minial Roll Game Element Selection handler settings'
